#!/bin/bash
source $DOTFILES/bash/config.sh
source $DOTFILES/urxvt/config.sh
source $DOTFILES/X11/config.sh
source $DOTFILES/xrandr/config.sh
source $DOTFILES/udiskie/config.sh
source $DOTFILES/fonts/config.sh
source $DOTFILES/i3/config.sh
source $DOTFILES/pulse/config.sh
source $DOTFILES/brightnessctl/config.sh
source $DOTFILES/rofi/config.sh
source $DOTFILES/zsh/config.sh
source $DOTFILES/dunst/config.sh
source $DOTFILES/git/config.sh
source $DOTFILES/nvim/config.sh
source $DOTFILES/tmux/config.sh
source $DOTFILES/redshift/config.sh
source $DOTFILES/rtorrent/config.sh
source $DOTFILES/julia/config.sh
source $DOTFILES/zathura/config.sh
