# XDG Base Directories
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_LOCAL_HOME="$HOME/.local"
export XDG_DATA_HOME="$XDG_LOCAL_HOME/share"
export XDG_STATE_HOME="$XDG_LOCAL_HOME/state"
export XDG_BIN_HOME="$XDG_LOCAL_HOME/bin"
export XDG_SCRIPTS_HOME="$XDG_CONFIG_HOME/scripts"

# XDG User Directories
export XDG_DOCUMENTS_DIR="$HOME/documents"
export XDG_DOWNLOAD_DIR="$HOME/downloads"
#export XDG_MUSIC_DIR="$HOME/music"
#export XDG_PICTURES_DIR="$HOME/pictures"
#export XDG_TEMPLATES_DIR="$HOME/templates"
export XDG_VIDEOS_DIR="$HOME/videos"
export XDG_WORK_DIR="$HOME/work"
export XDG_DATA_DIR="$HOME/data"
export XDG_RECORDINGS_DIR="$HOME/recordings"
export XDG_SCREENSHOTS_DIR="$HOME/screenshots"

# Dotfiles
export DOTFILES="$HOME/dotfiles"

# Set the default editor
export EDITOR="nvim"
export VISUAL="nvim"

# Zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

# History filepath
export HISTFILE="$ZDOTDIR/.zhistory"

# Maximum events for internal history
export HISTSIZE=10000

# Maximum events in history file
export SAVEHIST=10000
