# Merge Xresources
xrdb -merge $HOME/.config/X11/.Xresources

# TODO: map Caps_Lock to Super_L
#setxkbmap -option 'caps:ctrl_modifier'
#setxkbmap -option 'caps:win_space_toggle'
#xcape -e 'Caps_Lock=Escape' &

# Map Caps Lock to Escape
setxkbmap -option caps:escape

# Disable screen saver
xset s off
xset s noblank
xset -dpms

# Start rxvt-unicode daemon
urxvtd -o -q -f

# Start udiskie on the background
#udiskie --no-automount &

# Start i3 window manager
exec i3
