# Merge Xresources
#xrdb -merge $HOME/.config/X11/.Xresources
xrdb -merge $HOME/.config/X11/style.xresources
xrdb -merge $HOME/.config/X11/urxvt.xresources

# TODO: map Caps_Lock to Super_L
#setxkbmap -option 'caps:ctrl_modifier'
#setxkbmap -option 'caps:win_space_toggle'
#xcape -e 'Caps_Lock=Escape' &

# Map Caps Lock to Escape
setxkbmap -option caps:escape

# Disable screen saver
xset s off
xset s noblank
xset -dpms

# Start rxvt-unicode daemon
urxvtd -o -q -f

# Start i3 window manager
exec i3
