#!/urs/bin/env/bash 

## list directories
alias d='dirs -v'
for index ({1..9}) alias "$index"="cd +${index}"; unset index

## list files
alias ls='ls --color=auto'
alias ll='ls -lah --group-directories-first'

## grep
alias grep='grep --color=auto'

## tmux
alias tmuxl='tmux list-sessions'
alias tmuxa='tmux attach-session'
alias tmuxk='tmux kill-session'

## pacman and yay
alias pacman='pacman --color=auto'
alias yay='yay --color=auto'

## Git
alias gs='git status'
alias gd='git diff'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
