# For configuration files 
export XDG_CONFIG_HOME="$HOME/.config"

# For user specific data
export XDG_DATA_HOME="$XDG_CONFIG_HOME/local/share"

# For user cached files
export XDG_CACHE_HOME="$XDG_CONFIG_HOME/cache"

# For user downloads
export XDG_DOWNLOAD_DIR="$HOME/downloads"

# Dotfiles
export DOTFILES="$HOME/dotfiles"

# Directory for custom scripts
export SCRIPTS_DIR="$XDG_CONFIG_HOME/scripts"

# Set the default editor
export EDITOR="nvim"
export VISUAL="nvim"

# Zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

# History filepath
export HISTFILE="$ZDOTDIR/.zhistory"

# Maximum events for internal history
export HISTSIZE=10000

# Maximum events in history file
export SAVEHIST=10000
