#!/bin/zsh 

fpath=($ZDOTDIR/external $fpath)


## --- Aliases ---
source "$XDG_CONFIG_HOME/zsh/aliases.sh"
source "$XDG_CONFIG_HOME/pacman/aliases.sh"
source "$XDG_CONFIG_HOME/yay/aliases.sh"
source "$XDG_CONFIG_HOME/tmux/aliases.sh"
source "$XDG_CONFIG_HOME/git/aliases.sh"


## --- Custom Scripts ---
source "$XDG_CONFIG_HOME/zsh/scripts.sh"
source "$XDG_CONFIG_HOME/tmux/scripts.sh"


## --- Colors ---
eval "$(dircolors -b $XDG_CONFIG_HOME/zsh/dircolors)"


## --- Filesystem Navigation ---
source "$XDG_CONFIG_HOME/zsh/external/bd.zsh"

# Push the current directory visited on to the stack.
setopt AUTO_PUSHD

# Do not store duplicate directories in the stack
setopt PUSHD_IGNORE_DUPS

# Do not print the directory stack after using
setopt PUSHD_SILENT


## --- Command Completion ---
source $XDG_CONFIG_HOME/zsh/external/completion.zsh
zmodload zsh/complist
autoload -Uz compinit; compinit
_comp_options+=(globdots) # With hidden files


## --- Prompt ---
autoload -Uz prompt_purification_setup; prompt_purification_setup


## --- VIM Keymap ---
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -v
export KEYTIMEOUT=1
autoload -Uz cursor_mode && cursor_mode
autoload -Uz edit-command-line
zle -N edit-command-line
bindkey -M vicmd v edit-command-line


## --- FZF ---
if [ $(command -v "fzf") ]; then
    source /usr/share/fzf/completion.zsh
    source /usr/share/fzf/key-bindings.zsh
fi


## --- Key Bindings ---
# Unbind clearing shell from CTRL+l
bindkey -r '^l'
# Bind clearing shell to CTRL+g
bindkey -r '^g'
bindkey -s '^g' 'clear\n'
# Open tmux
bindkey -r '^p'
bindkey -s '^p' 'tmux\n'


## --- Syntax Highlighting ---
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

